import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import "./AddBook.css";

// 1. IMPORT HOOKS
import { useAddBook, useUpdateBook, useGetBookById, useGetBook } from "../../hooks/useBook";
import { useGetAllCategories } from "../../hooks/useCategory";

export default function BookForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditMode = Boolean(id);

  // Lấy danh sách sách để tạo mã tự động
  const { data: allBooksData } = useGetBook();
  const allBooks = allBooksData || [];

  // 2. GỌI HOOK LẤY DỮ LIỆU (Khi Edit)
  const { 
    data: bookData, 
    isLoading: isLoadingBook,
    isError: isErrorBook 
  } = useGetBookById(id, {
    enabled: isEditMode,
  });

  // 3. GỌI HOOK LẤY DANH MỤC
  const { 
    data: categoriesData, 
    isLoading: isLoadingCategories 
  } = useGetAllCategories();
  
  const categories = categoriesData || [];

  // 4. GỌI HOOK HÀNH ĐỘNG
  const { mutate: addBook, isPending: isAdding } = useAddBook();
  const { mutate: updateBook, isPending: isUpdating } = useUpdateBook();

  const isSubmitting = isAdding || isUpdating;

  const [formData, setFormData] = useState({
    title: "",
    author: "",
    bookCode: "",
    quantity: 1,
    genre: "",
    description: "",
    image: "",
  });

  const [errors, setErrors] = useState({});
  const [autoGeneratedCode, setAutoGeneratedCode] = useState(""); // Lưu mã đã tạo


  const generateBookCode = () => {
    if (allBooks.length === 0) return "B001";
    
    // Lấy tất cả mã sách bắt đầu bằng 'B' và có số
    const allCodes = allBooks
      .map(book => book.bookCode)
      .filter(code => code && /^B\d+$/i.test(code));
    
    // Tìm số lớn nhất
    let maxNumber = 0;
    allCodes.forEach(code => {
      const num = parseInt(code.substring(1));
      if (num > maxNumber) maxNumber = num;
    });
    
    // Tạo mã mới
    const newNumber = maxNumber + 1;
    return `B${newNumber.toString().padStart(3, '0')}`;
  };

  // --- EFFECT: TẠO MÃ KHI MỞ FORM THÊM MỚI ---
  useEffect(() => {
    if (!isEditMode && allBooks.length > 0) {
      const newCode = generateBookCode();
      setAutoGeneratedCode(newCode); // Lưu mã đã tạo
      setFormData(prev => ({
        ...prev,
        bookCode: newCode // Cập nhật vào form data
      }));
    }
  }, [allBooks, isEditMode]);

  // --- EFFECT: ĐIỀN DỮ LIỆU KHI EDIT ---
  useEffect(() => {
    if (isEditMode && bookData) {
      setFormData({
        title: bookData.title || "",
        author: bookData.author || "",
        bookCode: bookData.bookCode || "",
        quantity: bookData.quantity || 1,
        genre: bookData.genre?._id || bookData.genre || "",
        description: bookData.description || "",
        image: bookData.image || "",
      });
    }
  }, [isEditMode, bookData]);

  // --- XỬ LÝ UPLOAD ẢNH ---
  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    
    if (!file.type.startsWith('image/')) {
      alert('Vui lòng chọn file ảnh!');
      return;
    }
    
    if (file.size > 2 * 1024 * 1024) {
      alert('Kích thước ảnh không được vượt quá 2MB');
      return;
    }
    
    const reader = new FileReader();
    reader.onloadend = () => {
      setFormData({ ...formData, image: reader.result });
    };
    reader.onerror = () => {
      alert('Lỗi đọc file ảnh!');
    };
    reader.readAsDataURL(file);
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === "quantity" ? parseInt(value) || 0 : value,
    }));

    // Xóa lỗi khi gõ
    if (errors[name]) {
      setErrors({ ...errors, [name]: "" });
    }
  };

  // Validate
  const validateForm = () => {
    const newErrors = {};
    if (!formData.title.trim()) newErrors.title = "Tên sách bắt buộc";
    if (!formData.author.trim()) newErrors.author = "Tác giả bắt buộc";
    if (!formData.bookCode.trim()) newErrors.bookCode = "Mã sách bắt buộc";
    if (formData.quantity < 1) newErrors.quantity = "Số lượng phải > 0";
    if (!formData.genre) newErrors.genre = "Vui lòng chọn thể loại";

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validateForm()) return;

    // Khi thêm mới, đảm bảo có mã sách
    const finalBookCode = isEditMode 
      ? formData.bookCode 
      : autoGeneratedCode || generateBookCode();

    const payload = {
      title: formData.title.trim(),
      author: formData.author.trim(),
      bookCode: finalBookCode.trim(),
      quantity: formData.quantity,
      genre: formData.genre,
      description: formData.description.trim(),
      image: formData.image || `https://ui-avatars.com/api/?name=${encodeURIComponent(formData.title)}&background=random&color=fff&size=128`,
    };

    if (isEditMode) {
      updateBook(
        { id, data: payload },
        {
          onSuccess: () => {
            alert("Cập nhật thành công!");
            navigate("/manage/books");
          },
          onError: (err) => {
            const errorMessage = err.response?.data?.message || err.message || "Có lỗi xảy ra";
            alert("Lỗi: " + errorMessage);
          },
        }
      );
    } else {
      addBook(payload, {
        onSuccess: () => {
          alert("Thêm sách thành công!");
          navigate("/manage/books");
        },
        onError: (err) => {
          const errorMessage = err.response?.data?.message || err.message || "Có lỗi xảy ra";
          alert("Lỗi: " + errorMessage);
        },
      });
    }
  };

  // Loading states
  if (isEditMode && isLoadingBook) return <div className="loading">Đang tải thông tin sách...</div>;
  if (isEditMode && isErrorBook) return <div className="error">Không thể tải thông tin sách</div>;
  if (isLoadingCategories) return <div className="loading">Đang tải danh mục...</div>;

  return (
    <div className="book-form-page">
      <div className="form-header">
        <h1>{isEditMode ? "Chỉnh Sửa Sách" : "Thêm Sách Mới"}</h1>
        <button className="back-btn" onClick={() => navigate("/manage/books")}>
          ← Quay lại
        </button>
      </div>

      <form onSubmit={handleSubmit} className="book-form">
        <div className="form-row">
          <div className="form-group">
            <label htmlFor="title">Tên sách *</label>
            <input
              type="text"
              id="title"
              name="title"
              value={formData.title}
              onChange={handleChange}
              className={errors.title ? "error" : ""}
              placeholder="Nhập tên sách"
              disabled={isSubmitting}
            />
            {errors.title && (
              <span className="error-message">{errors.title}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="author">Tác giả *</label>
            <input
              type="text"
              id="author"
              name="author"
              value={formData.author}
              onChange={handleChange}
              className={errors.author ? "error" : ""}
              placeholder="Nhập tên tác giả"
              disabled={isSubmitting}
            />
            {errors.author && (
              <span className="error-message">{errors.author}</span>
            )}
          </div>
        </div>

        <div className="form-row">
          {/* CHỈ CÓ THỂ LOẠI, KHÔNG CÓ MÃ SÁCH */}
          <div className="form-group">
            <label htmlFor="genre">Thể loại *</label>
            <select
              id="genre"
              name="genre"
              value={formData.genre}
              onChange={handleChange}
              className={errors.genre ? "error" : ""}
              disabled={isSubmitting || isLoadingCategories}
            >
              <option value="">-- Chọn thể loại --</option>
              {categories.map((cat) => (
                <option key={cat._id} value={cat._id}>
                  {cat.name}
                </option>
              ))}
            </select>
            {errors.genre && (
              <span className="error-message">{errors.genre}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="quantity">Tổng số lượng *</label>
            <input
              type="number"
              id="quantity"
              name="quantity"
              value={formData.quantity}
              onChange={handleChange}
              className={errors.quantity ? "error" : ""}
              min="1"
              disabled={isSubmitting}
            />
            {errors.quantity && (
              <span className="error-message">{errors.quantity}</span>
            )}
          </div>
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>Ảnh bìa:</label>
            <input 
              type="file" 
              accept="image/*" 
              onChange={handleImageUpload} 
              disabled={isSubmitting}
            />
            {formData.image && (
              <div className="image-preview">
                <img
                  src={formData.image}
                  alt="Preview"
                  className="preview-image"
                />
                <button 
                  type="button" 
                  className="remove-image-btn"
                  onClick={() => setFormData({...formData, image: ""})}
                  disabled={isSubmitting}
                >
                  Xóa ảnh
                </button>
              </div>
            )}
          </div>

          {/* Dummy column để layout đẹp */}
          <div className="form-group"></div>
        </div>

        <div className="form-group full-width">
          <label htmlFor="description">Mô tả</label>
          <textarea
            id="description"
            name="description"
            value={formData.description}
            onChange={handleChange}
            placeholder="Nhập mô tả..."
            rows="4"
            disabled={isSubmitting}
          />
        </div>

        <div className="form-actions">
          <button
            type="button"
            className="cancel-btn"
            onClick={() => navigate("/manage/books")}
            disabled={isSubmitting}
          >
            Hủy
          </button>
          <button type="submit" className="submit-btn" disabled={isSubmitting}>
            {isSubmitting
              ? "Đang lưu..."
              : isEditMode
              ? "Cập nhật"
              : "Thêm sách"}
          </button>
        </div>
      </form>
    </div>
  );
}
